/*

 LEVEL006_OBJECTS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 11
   Tile set      : Z:\home\xubuntu\gbdk\Tools\turtleSprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define levelObjects006Width 12
#define levelObjects006Height 11
#define levelObjects006Bank 0

extern unsigned char levelObjects006[];

/* End of LEVEL006_OBJECTS.H */
