/*

 LEVEL008.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 11
   Tile set      : Z:\home\xubuntu\gbdk\Tools\turtle.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level008Width 12
#define level008Height 11
#define level008Bank 0

extern unsigned char level008[];

/* End of LEVEL008.H */
