/*

 LEVEL007_OBJECTS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 11
   Tile set      : Z:\home\xubuntu\gbdk\Tools\turtleSprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define levelObjects007Width 12
#define levelObjects007Height 11
#define levelObjects007Bank 0

extern unsigned char levelObjects007[];

/* End of LEVEL007_OBJECTS.H */
