/*

 LEVEL010.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 11
   Tile set      : Z:\home\xubuntu\gbdk\Tools\turtle.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level010Width 12
#define level010Height 11
#define level010Bank 0

extern unsigned char level010[];

/* End of LEVEL010.H */
