/*

 CGBONLYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\xubuntu\gbdk\Tools\cgbolny.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cgbOnlyMapWidth 20
#define cgbOnlyMapHeight 18
#define cgbOnlyMapBank 0

extern unsigned char cgbOnlyMap[];

/* End of CGBONLYMAP.H */
