/*

 GAMEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\Tools\turtle.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gameMapWidth 20
#define gameMapHeight 18
#define gameMapBank 0

extern unsigned char gameMap[];

/* End of GAMEMAP.H */
