/*

 GAMEMAPPALETTE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\Tools\turtle.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gameMapPaletteWidth 20
#define gameMapPaletteHeight 18
#define gameMapPaletteBank 0

extern unsigned char gameMapPalette[];

/* End of GAMEMAPPALETTE.H */
