/*

 TURTLESPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define turtleSpritesBank 0

/* Super Gameboy palette 0 */
#define turtleSpritesSGBPal0c0 6076
#define turtleSpritesSGBPal0c1 8935
#define turtleSpritesSGBPal0c2 6596
#define turtleSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define turtleSpritesSGBPal1c0 6076
#define turtleSpritesSGBPal1c1 8935
#define turtleSpritesSGBPal1c2 6596
#define turtleSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define turtleSpritesSGBPal2c0 6076
#define turtleSpritesSGBPal2c1 8935
#define turtleSpritesSGBPal2c2 6596
#define turtleSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define turtleSpritesSGBPal3c0 6076
#define turtleSpritesSGBPal3c1 8935
#define turtleSpritesSGBPal3c2 6596
#define turtleSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define turtleSpritesCGBPal0c0 32767
#define turtleSpritesCGBPal0c1 15855
#define turtleSpritesCGBPal0c2 5311
#define turtleSpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define turtleSpritesCGBPal1c0 32767
#define turtleSpritesCGBPal1c1 15855
#define turtleSpritesCGBPal1c2 992
#define turtleSpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define turtleSpritesCGBPal2c0 32767
#define turtleSpritesCGBPal2c1 15855
#define turtleSpritesCGBPal2c2 32074
#define turtleSpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define turtleSpritesCGBPal3c0 6076
#define turtleSpritesCGBPal3c1 8935
#define turtleSpritesCGBPal3c2 6596
#define turtleSpritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define turtleSpritesCGBPal4c0 6076
#define turtleSpritesCGBPal4c1 8935
#define turtleSpritesCGBPal4c2 6596
#define turtleSpritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define turtleSpritesCGBPal5c0 6076
#define turtleSpritesCGBPal5c1 8935
#define turtleSpritesCGBPal5c2 6596
#define turtleSpritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define turtleSpritesCGBPal6c0 6076
#define turtleSpritesCGBPal6c1 8935
#define turtleSpritesCGBPal6c2 6596
#define turtleSpritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define turtleSpritesCGBPal7c0 6076
#define turtleSpritesCGBPal7c1 8935
#define turtleSpritesCGBPal7c2 6596
#define turtleSpritesCGBPal7c3 5344

/* CGB palette entries. */
#define turtleSpritesCGB0 0
#define turtleSpritesCGB1 0
#define turtleSpritesCGB2 0
#define turtleSpritesCGB3 0
#define turtleSpritesCGB4 0
#define turtleSpritesCGB5 0
#define turtleSpritesCGB6 0
#define turtleSpritesCGB7 0
/* Start of tile array. */
extern unsigned char turtleSprites[];

/* End of TURTLESPRITES.H */
