/*

 TURTLETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 56

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define turtleTilesBank 0

/* Super Gameboy palette 0 */
#define turtleTilesSGBPal0c0 6076
#define turtleTilesSGBPal0c1 8935
#define turtleTilesSGBPal0c2 6596
#define turtleTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define turtleTilesSGBPal1c0 6076
#define turtleTilesSGBPal1c1 8935
#define turtleTilesSGBPal1c2 6596
#define turtleTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define turtleTilesSGBPal2c0 6076
#define turtleTilesSGBPal2c1 8935
#define turtleTilesSGBPal2c2 6596
#define turtleTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define turtleTilesSGBPal3c0 6076
#define turtleTilesSGBPal3c1 8935
#define turtleTilesSGBPal3c2 6596
#define turtleTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define turtleTilesCGBPal0c0 32767
#define turtleTilesCGBPal0c1 21140
#define turtleTilesCGBPal0c2 10570
#define turtleTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define turtleTilesCGBPal1c0 32767
#define turtleTilesCGBPal1c1 5311
#define turtleTilesCGBPal1c2 1002
#define turtleTilesCGBPal1c3 31909

/* Gameboy Color palette 2 */
#define turtleTilesCGBPal2c0 32767
#define turtleTilesCGBPal2c1 5311
#define turtleTilesCGBPal2c2 1002
#define turtleTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define turtleTilesCGBPal3c0 32767
#define turtleTilesCGBPal3c1 5311
#define turtleTilesCGBPal3c2 31909
#define turtleTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define turtleTilesCGBPal4c0 32767
#define turtleTilesCGBPal4c1 1002
#define turtleTilesCGBPal4c2 5311
#define turtleTilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define turtleTilesCGBPal5c0 32767
#define turtleTilesCGBPal5c1 1002
#define turtleTilesCGBPal5c2 31909
#define turtleTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define turtleTilesCGBPal6c0 32767
#define turtleTilesCGBPal6c1 31909
#define turtleTilesCGBPal6c2 5311
#define turtleTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define turtleTilesCGBPal7c0 32767
#define turtleTilesCGBPal7c1 31909
#define turtleTilesCGBPal7c2 1002
#define turtleTilesCGBPal7c3 0

/* CGB palette entries. */
#define turtleTilesCGB0 1
#define turtleTilesCGB1 1
#define turtleTilesCGB2 1
#define turtleTilesCGB3 1
#define turtleTilesCGB4 0
#define turtleTilesCGB5 0
#define turtleTilesCGB6 0
#define turtleTilesCGB7 0
#define turtleTilesCGB8 0
#define turtleTilesCGB9 0
#define turtleTilesCGB10 2
#define turtleTilesCGB11 0
#define turtleTilesCGB12 0
#define turtleTilesCGB13 0
#define turtleTilesCGB14 0
#define turtleTilesCGB15 0
#define turtleTilesCGB16 0
#define turtleTilesCGB17 0
#define turtleTilesCGB18 0
#define turtleTilesCGB19 0
#define turtleTilesCGB20 0
#define turtleTilesCGB21 0
#define turtleTilesCGB22 0
#define turtleTilesCGB23 0
#define turtleTilesCGB24 0
#define turtleTilesCGB25 0
#define turtleTilesCGB26 0
#define turtleTilesCGB27 0
#define turtleTilesCGB28 0
#define turtleTilesCGB29 0
#define turtleTilesCGB30 0
#define turtleTilesCGB31 0
#define turtleTilesCGB32 0
#define turtleTilesCGB33 0
#define turtleTilesCGB34 2
#define turtleTilesCGB35 2
#define turtleTilesCGB36 2
#define turtleTilesCGB37 2
#define turtleTilesCGB38 2
#define turtleTilesCGB39 2
#define turtleTilesCGB40 2
#define turtleTilesCGB41 0
#define turtleTilesCGB42 0
#define turtleTilesCGB43 0
#define turtleTilesCGB44 0
#define turtleTilesCGB45 0
#define turtleTilesCGB46 0
#define turtleTilesCGB47 2
#define turtleTilesCGB48 0
#define turtleTilesCGB49 0
#define turtleTilesCGB50 0
#define turtleTilesCGB51 0
#define turtleTilesCGB52 0
#define turtleTilesCGB53 0
#define turtleTilesCGB54 0
#define turtleTilesCGB55 0
#define turtleTilesCGB56 0
/* Start of tile array. */
extern unsigned char turtleTiles[];

/* End of TURTLETILES.H */
